# Generated by Django 5.2.1 on 2025-06-08 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_categories_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journals',
            name='image',
        ),
        migrations.RemoveField(
            model_name='papers',
            name='image',
        ),
    ]
