# Generated by Django 5.2.1 on 2025-06-10 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0002_alter_author_photo_alter_author_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='papers',
            name='reference',
        ),
    ]
