# Generated by Django 5.2.1 on 2025-06-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0003_remove_papers_reference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='journals',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
