# Generated by Django 5.2.1 on 2025-06-10 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0004_alter_journals_download_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='papers',
            name='download_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
