# Generated by Django 5.2.1 on 2025-06-10 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('journals', '0005_alter_papers_download_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='journals',
            old_name='article',
            new_name='article_ru',
        ),
        migrations.RenameField(
            model_name='journals',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.RenameField(
            model_name='papers',
            old_name='article',
            new_name='article_ru',
        ),
        migrations.RenameField(
            model_name='papers',
            old_name='title',
            new_name='title_ru',
        ),
        migrations.AddField(
            model_name='journals',
            name='article_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='journals',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='article_uz',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='papers',
            name='title_uz',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
